version: '3'

services:
  mongo:
    image: mongo:4.0.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  app:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      mongo:
        condition: service_healthy